services:
  searxng:
    image: docker.io/searxng/searxng:latest
    volumes:
      - ./searxng:/etc/searxng:rw
    ports:
      - 4000:8080
    networks:
      - internal
    restart: unless-stopped

  app:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env.local
    environment:
      NEXTAUTH_URL: http://localhost:3000
      NEXTAUTH_SECRET: ${AUTH_SECRET}
      NEXTAUTH_URL_INTERNAL: http://app:3000
      NODE_ENV: development
    depends_on:
      searxng:
        condition: service_healthy
    volumes:
      - data:/home/open-deep-research/data

networks:
  internal:

volumes:
  data:
