name: deepresearch-py
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pip>=2.0

  # Conda-managed dependencies
  - conda-forge::antlr4-python3-runtime
  - conda-forge::numpy
  - conda-forge::nltk
  - conda-forge::scikit-learn
  - conda-forge::scipy
  - pip:
      # Brotli for HTTP decompression
      - Brotli
      # PyTorch for CUDA (Ensure version matches your CUDA install)
      # Check https://pytorch.org/ for specific command if needed
      - --extra-index-url https://download.pytorch.org/whl/cu118
      - torch
      - torchaudio
      - torchvision

      # Core Flask and Web (Keep pinned for stability)
      - flask==2.3.3
      - requests==2.31.0

      # Embeddings & Reranking (Unpin sentence-transformers)
      - sentence-transformers
      - transformers
      - einops
      # Optional: For Flash Attention speedup on compatible GPUs
      # - ninja
      # - flash-attn --no-build-isolation

      # Document Loading & Scraping (Including crawl4ai deps)
      - pypdf
      - pymupdf
      - unstructured
      - unstructured-inference
      - beautifulsoup4
      - markdown
      - crawl4ai
      - playwright
      - huggingface_hub
      - wikipedia-api
      - fasttext-wheel

      # Utilities
      - python-dotenv==1.0.0

      # Langchain
      - langchain-community
      - langchain
      - langchain-text-splitters
