name: deepresearch-py
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pip>=23.0
  - conda-forge::antlr4-python3-runtime # Keep this
  - conda-forge::numpy=1.24.3
  - pip:
      # PyTorch for CUDA 11.8
      - --extra-index-url https://download.pytorch.org/whl/cu118
      - torch
      - torchaudio
      - torchvision

      # Core Flask and Web
      - flask==2.3.3
      - requests==2.31.0

      # Embeddings
      - sentence-transformers==2.2.2

      # Document Loading (Dependencies might be handled by conda install now)
      - pypdf==3.15.1
      - pymupdf==1.22.5
      - unstructured==0.10.30
      - unstructured-inference==0.7.12
      - beautifulsoup4==4.12.2
      - markdown==3.4.4

      # Utilities
      - python-dotenv==1.0.0

      # Langchain
      - langchain-community==0.0.10
      - langchain==0.1.0
